export const LOG_IN_USER_REQUEST = 'LOG_IN_USER_REQUEST';
export const LOG_IN_USER_SUCCESS = 'LOG_IN_USER_SUCCESS';
export const LOG_IN_USER_FAILURE = 'LOG_IN_USER_FAILURE';

export const LOG_OUT_USER_REQUEST = 'LOG_OUT_USER_REQUEST';
export const LOG_OUT_USER_SUCCESS = 'LOG_OUT_USER_SUCCESS';
export const LOG_OUT_USER_FAILURE = 'LOG_OUT_USER_FAILURE';

export const SIGN_UP_USER_REQUEST = 'SIGN_UP_USER_REQUEST';
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
export const SIGN_UP_USER_FAILURE = 'SIGN_UP_USER_FAILURE';

export const LOAD_STATE_FROM_LOCAL = 'LOAD_STATE_FROM_LOCAL';

export const GET_ALL_PRODUCTS_REQUEST = 'GET_ALL_PRODUCTS_REQUEST';
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS';

export const GET_ALL_WISH_LIST_REQUEST = 'GET_ALL_WISH_LIST_REQUEST';
export const POST_ALL_WISH_LIST_REQUEST = 'POST_ALL_WISH_LIST_REQUEST';
export const DELETE_ALL_WISH_LIST_REQUEST = 'DELETE_ALL_WISH_LIST_REQUEST';

export const WISH_LIST_FAILURE = 'WISH_LIST_FAILURE';
export const WISH_LIST_SUCCESS = 'WISH_LIST_SUCCESS';
export const WISH_LIST_RESET = 'WISH_LIST_RESET';