export const LOG_IN_USER_REQUEST = 'LOG_IN_USER_REQUEST';
export const LOG_IN_USER_SUCCESS = 'LOG_IN_USER_SUCCESS';
export const LOG_IN_USER_FAILURE = 'LOG_IN_USER_FAILURE';

export const LOG_OUT_USER_REQUEST = 'LOG_OUT_USER_REQUEST';
export const LOG_OUT_USER_SUCCESS = 'LOG_OUT_USER_SUCCESS';
export const LOG_OUT_USER_FAILURE = 'LOG_OUT_USER_FAILURE';

export const LOAD_STATE_FROM_LOCAL = 'LOAD_STATE_FROM_LOCAL';

export const LOG_OUT_USER = 'LOG_OUT_USER';

export const GET_PRODUCTS = 'GET_PRODUCTS';